services:
  - type: web
    name: ecoglow
    env: docker
    repo: https://github.com/Sy4ffikana/ecoglow
    branch: main
    buildCommand: ""
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: ecoglow
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: SYaFF_5112
